apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: go-server
    newName: 658310026229.dkr.ecr.us-west-2.amazonaws.com/stateless-app-go
    newTag: latest

  - name: swift-server
    newName: 658310026229.dkr.ecr.us-west-2.amazonaws.com/stateless-app-swift
    newTag: latest