apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - envoy-admin-service.yaml
  - grafana-service.yaml
  - grafana-datasource.yaml
  - grafana-deployment.yaml